name: "Terragrunt infrastructure pipeline with GitHub Actions"

on: 
  push: 
    branches:
    - main
    paths:
    - env/**
    #- modules/**
  pull_request:
    branches:
    - main
    paths:
    - env/**
    #- modules/**

env: 
  TF_LOG: INFO
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  TERRAFORM_VERSION: 1.4.2
  TERRAGRUNT_VERSION: v0.55.1

jobs:
  terragrunt-plan-apply-all-sandbox:
    name: "terragrunt-plan-apply-all-sandbox"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      
      - name: Terraform version
        run: terraform --version

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          bin/terragrunt -v
      
      - name: add SSH private key    
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Plan All sandbox
        run: |
          cd env/sandbox
          terragrunt run-all plan -out tf.plan --terragrunt-non-interactive 

      - name: Apply All sandbox
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd env/sandbox
          terragrunt run-all apply tf.plan --terragrunt-non-interactive    